import { IDirection } from 'src/direction/models/direction.dto';
import { IOrder } from 'src/orders/models/order.dto';
import { ITarif } from 'src/tarifs/models/tarif.dto';

export const testTarifs: ITarif[] = [
  {
    name: 'Эконом',
    dataBtn: 'setup.tarif.econom',
  },
  {
    name: 'Стандарт',
    dataBtn: 'setup.tarif.standart',
  },
  {
    name: 'Комфорт',
    dataBtn: 'setup.tarif.comfort',
  },
  {
    name: 'Микровэн',
    dataBtn: 'setup.tarif.microven',
  },
  {
    name: 'Минивэн',
    dataBtn: 'setup.tarif.miniven',
  },
  {
    name: 'Комфорт+',
    dataBtn: 'setup.tarif.comfort.d',
  },
  {
    name: 'Бизнес',
    dataBtn: 'setup.tarif.business.e',
  },
  {
    name: 'Бизнес минивэн',
    dataBtn: 'setup.tarif.business.v',
  },
  {
    name: 'Бизнес+',
    dataBtn: 'setup.tarif.business.s',
  },
  {
    name: 'Микроавтобус',
    dataBtn: 'setup.tarif.microavtobus',
  },
  {
    name: 'Автобус',
    dataBtn: 'setup.tarif.avtobus',
  },
  {
    name: 'Эвакуатор / Манипулятор',
    dataBtn: 'setup.tarif.evacuator',
  },
];

export const testOrders: IOrder[] = [
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Алушта',
    fromCode: 'setup.direction.alushta',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эконом',
    tarifCode: 'setup.tarif.econom',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Анапа',
    fromCode: 'setup.direction.anapa',
    to: 'Торез (Донецкая область)',
    tarifName: 'Стандарт',
    tarifCode: 'setup.tarif.standart',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Астрахань',
    fromCode: 'setup.direction.astrakhan',
    to: 'Торез (Донецкая область)',
    tarifName: 'Комфорт',
    tarifCode: 'setup.tarif.comfort',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Геленджик',
    fromCode: 'setup.direction.gelendzhik',
    to: 'Торез (Донецкая область)',
    tarifName: 'Микровэн',
    tarifCode: 'setup.tarif.microven',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Джанкой',
    fromCode: 'setup.direction.dzhankoy',
    to: 'Торез (Донецкая область)',
    tarifName: 'Минивэн',
    tarifCode: 'setup.tarif.miniven',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Евпатория',
    fromCode: 'setup.direction.evpatoria',
    to: 'Торез (Донецкая область)',
    tarifName: 'Комфорт+',
    tarifCode: 'setup.tarif.comfort.d',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Екатеринбург',
    fromCode: 'setup.direction.ekaterinburg',
    to: 'Торез (Донецкая область)',
    tarifName: 'Бизнес',
    tarifCode: 'setup.tarif.business.e',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Казань',
    fromCode: 'setup.direction.kazan',
    to: 'Торез (Донецкая область)',
    tarifName: 'Бизнес минивэн',
    tarifCode: 'setup.tarif.business.v',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Керчь',
    fromCode: 'setup.direction.kerch',
    to: 'Торез (Донецкая область)',
    tarifName: 'Бизнес+',
    tarifCode: 'setup.tarif.business.s',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Краснодар',
    fromCode: 'setup.direction.krasnodar',
    to: 'Торез (Донецкая область)',
    tarifName: 'Микроавтобус',
    tarifCode: 'setup.tarif.microavtobus',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Махачкала',
    fromCode: 'setup.direction.makhachkala',
    to: 'Торез (Донецкая область)',
    tarifName: 'Автобус',
    tarifCode: 'setup.tarif.avtobus',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Минск',
    fromCode: 'setup.direction.minsk',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Москва',
    fromCode: 'setup.direction.moscow',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Новороссийск',
    fromCode: 'setup.direction.novorossiysk',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Новосибирск',
    fromCode: 'setup.direction.novosibirsk',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Порт Кавказ',
    fromCode: 'setup.direction.port_kavkaz',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Ростов на Дону',
    fromCode: 'setup.direction.rostov_on_don',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Санкт-Петербург',
    fromCode: 'setup.direction.saint_petersburg',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Севастополь',
    fromCode: 'setup.direction.sevastopol',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Симферополь',
    fromCode: 'setup.direction.simferopol',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Сочи',
    fromCode: 'setup.direction.sochi',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Ставраполь',
    fromCode: 'setup.direction.stavropol',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Феодосия',
    fromCode: 'setup.direction.feodosia',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
  {
    date: '2023-12-20T23:43:41+03:00',
    fromName: 'Ялта',
    fromCode: 'setup.direction.yalta',
    to: 'Торез (Донецкая область)',
    tarifName: 'Эвакуатор / Манипулятор',
    tarifCode: 'setup.tarif.evacuator',
    price: '14500',
    passenger: 2,
    numberOrder: '22698',
  },
];

export const testDirection: IDirection[] = [
  {
    directionName: 'Алушта',
    directionCode: 'setup.direction.alushta',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Анапа',
    directionCode: 'setup.direction.anapa',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Астрахань',
    directionCode: 'setup.direction.astrakhan',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Геленджик',
    directionCode: 'setup.direction.gelendzhik',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Джанкой',
    directionCode: 'setup.direction.dzhankoy',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Евпатория',
    directionCode: 'setup.direction.evpatoria',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Екатеринбург',
    directionCode: 'setup.direction.ekaterinburg',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Казань',
    directionCode: 'setup.direction.kazan',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Керчь',
    directionCode: 'setup.direction.kerch',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Краснодар',
    directionCode: 'setup.direction.krasnodar',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Махачкала',
    directionCode: 'setup.direction.makhachkala',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Минск',
    directionCode: 'setup.direction.minsk',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Москва',
    directionCode: 'setup.direction.moscow',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Новороссийск',
    directionCode: 'setup.direction.novorossiysk',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Новосибирск',
    directionCode: 'setup.direction.novosibirsk',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Порт Кавказ',
    directionCode: 'setup.direction.port_kavkaz',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Ростов на Дону',
    directionCode: 'setup.direction.rostov_on_don',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Санкт-Петербург',
    directionCode: 'setup.direction.saint_petersburg',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Севастополь',
    directionCode: 'setup.direction.sevastopol',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Симферополь',
    directionCode: 'setup.direction.simferopol',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Сочи',
    directionCode: 'setup.direction.sochi',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Ставраполь',
    directionCode: 'setup.direction.stavropol',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Феодосия',
    directionCode: 'setup.direction.feodosia',
    directionFrom: 0,
    isSelect: false,
  },
  {
    directionName: 'Ялта',
    directionCode: 'setup.direction.yalta',
    directionFrom: 0,
    isSelect: false,
  },
];
